#!/bin/sh

mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys

busybox --install

depmod -a

find /sys -name modalias -exec cat \{\} \; \
| xargs /sbin/modprobe -a >/dev/null 2>/dev/null

modprobe -vv sd-mod
modprobe -vv loop
modprobe -vv fuse

# fix drive timeouts
for f in /sys/block/sd?/device/timeout; do
	echo 86400 > "$f"
done

# setup networking
ifconfig lo up
for i in $(ip a s | awk '/^[^ ]/ {print $2}' | sed -e s/://); do
	[ "$i" = "lo" ] && continue
	dhclient -v "$i"
done

# run the installer
/installer || exec /bin/bash

reboot -f
