#!/bin/bash

set -euo pipefail

[ -d /c ] || mkdir /c
[ -d /d ] || mkdir /d
[ -d /wim ] || mkdir /wim
[ -d /iso ] || mkdir /iso

dialog(){
	/usr/bin/dialog --backtitle "Windows.ova v. $(< /etc/version)" "$@"
}

version=""
localmirror=""

if mount /dev/sr0 /iso; then
	if [ -e /iso/variables.txt ]; then
		. /iso/variables.txt
		# strip linefeed incase the file is in dos format
		version="${version%%$'\r'}"
		localmirror="${localmirror%%$'\r'}"
	fi
fi

cmd="$(echo dialog --title '"Windows Version Selection"' --no-tags --radiolist '"Select a Windows version to install"' 20 60 13 $(awk -F, '{print $1,"\"" $2 "\"","off"}' /etc/versions) | sed 's/off/on/')"
if [ -z "$version" ]; then
	version="$(eval "$cmd" 3>&2 2>&1 1>&3)"
fi

# Allow just overriding of the Autounattend.xml file, based on version
if [ -e "/iso/${version}/Autounattend.xml" ]; then
	au="/iso/${version}/Autounattend.xml"
else
	au="/au/${version}.xml"
fi

if [ -z "$version" ]; then
	poweroff -f
fi

URL="$(awk -F, "\$1 == \"$version\" {print \$4}" /etc/versions)"
SHA1SUM="$(awk -F, "\$1 == \"$version\" {print \$3}" /etc/versions)"

if [ "$localmirror" != "none" ]; then
	localmirror="$(dialog --title "Mirror selection" --inputbox "Enter URL of local mirror. This can be left blank." 8 60 3>&2 2>&1 1>&3)"
else
	localmirror=""
fi

if [ -n "$localmirror" ]; then
	URL="$localmirror/$(basename "$URL")"
fi

mount /dev/sda1 /c
mkfs.ntfs -f -L data /dev/sdb1
mount /dev/sdb1 /d

cd /c
aria2c -x 8 -s 8 --file-allocation=prealloc  "$URL" -o "/${version}.iso"
sync

echo "Checking iso"
echo "$SHA1SUM /c/${version}.iso" | sha1sum -c >/dev/null
if [ $? != 0 ]; then
	echo "Checksum failed"
	read -r _
fi

cd /d
7z x "/c/${version}.iso"
wimmountrw /d/sources/boot.wim 2 /wim
cp "$au" /wim/Autounattend.xml
wimunmount --commit /wim
cd /

sync
sync
sync

until umount /d; do sync; sleep 1; done
until umount /c; do sync; sleep 1; done

exit 0
