#!/bin/bash

set -euo pipefail

[ -d /c ] || mkdir /c
[ -d /d ] || mkdir /d
[ -d /wim ] || mkdir /wim
[ -d /iso ] || mkdir /iso

dialog(){
	/usr/bin/dialog --backtitle "Windows.ova v. $(< /etc/version)" "$@"
}

version=""
if mount /dev/sr0 /iso; then
	if [ -e /iso/version.txt ]; then
		version="$(< /iso/version.txt)"
	fi
	if [ -e /iso/Autounattend.xml ]; then
		au="/iso/Autounattend.xml"
	else
		au="/au/${version}.xml"
	fi
fi

cmd="$(echo dialog --no-tags --radiolist '"Pick a version"' 20 60 13 $(awk -F, '{print $1,"\"" $2 "\"","off"}' /etc/versions) | sed 's/off/on/')"
if [ -z "$version" ]; then
	version="$(eval "$cmd" 3>&2 2>&1 1>&3)"
	au="/au/${version}.xml"
fi

if [ -z "$version" ]; then
	poweroff -f
fi

URL="$(awk -F, "\$1 == \"$version\" {print \$4}" /etc/versions)"
SHA1SUM="$(awk -F, "\$1 == \"$version\" {print \$3}" /etc/versions)"

localmirror="$(dialog --inputbox "Enter URL of local mirror. This can be left blank." 8 60 3>&2 2>&1 1>&3)"

if [ -n "$localmirror" ]; then
	URL="$localmirror/$(basename "$URL")"
fi

mount /dev/sda1 /c
mkfs.ntfs -f -L data /dev/sdb1
mount /dev/sdb1 /d

cd /c
aria2c -x 8 -s 8 --file-allocation=prealloc  "$URL" -o "/${version}.iso"
sync

echo "Checking iso"
echo "$SHA1SUM /c/${version}.iso" | sha1sum -c >/dev/null
if [ $? != 0 ]; then
	echo "Checksum failed"
	read -r _
fi

cd /d
7z x "/c/${version}.iso"
wimmountrw /d/sources/boot.wim 2 /wim
cp "$au" /wim/Autounattend.xml
wimunmount --commit /wim
cd /

sync
sync
sync

until umount /d; do sync; sleep 1; done
until umount /c; do sync; sleep 1; done

exit 0
